baseurl = "https://natecox.dev"
languageCode = "en-us"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Nathan Cox"
  keywords = "homepage, blog, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  homeSubtitle = "Full stack, polyglot, web development enthusiast."

  [[params.social]]
    name = "github"
    url = "https://github.com/natecox"
    
  [[params.social]]
    name = "stackoverflow"
    url = "https://stackoverflow.com/story/natecox"
    
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/nathanscox/"
    
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/tsuujin"
    
  [[params.social]]
    name = "email"
    url = "mailto:tsuujin@icloud.com"

[languages]
  [languages.en]
    title = "Nathan Cox"
    subtitle = "Thoughts and Musings?"
    keywords = "homepage, blog, development, programming"
    copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png"></a>'
    readotherposts = "read other posts"

    [languages.en.params.logo]
      logoText = "cd ~"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "posts/"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"
